const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_IN = 'SIGN_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const LOG_OUT = 'LOG_OUT';
const FETCH_ORDERS = 'FETCH_ORDERS';
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
const ADD_ORDER = 'ADD_ORDER';
const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';
const PAY_ORDER = 'PAY_ORDER';
const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
const PAY_ORDER_FAILURE = 'PAY_ORDER_FAILURE';




const actionTypes = {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    FILTER_PRODUCTS,
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILURE,
    SIGN_UP,
    SIGN_UP_SUCCESS,
    SIGN_UP_FAILURE,
    SIGN_IN,
    SIGN_IN_SUCCESS,
    SIGN_IN_FAILURE,
    LOG_OUT,
    FETCH_ORDERS,
    FETCH_ORDERS_SUCCESS,
    FETCH_ORDERS_FAILURE,
    ADD_ORDER,
    ADD_ORDER_SUCCESS,
    ADD_ORDER_FAILURE,
    PAY_ORDER,
    PAY_ORDER_SUCCESS,
    PAY_ORDER_FAILURE,
};

export default actionTypes;